config/routes.rb
SurveySupport::Application.routes.draw do
  authenticated :user do
    get "home/index", as: "home"
    root :to => 'home#index'
  end
  get "welcome/index", as: "welcome"
  root :to => 'welcome#index'
  
  devise_for :users  
  
  resources :events
  
  resources :people do
    resources :addresses
  end
  resources :surveys
  resources :cities
  resources :states
  resources :studies do
    member do
      get 'examinations'
    end
  end
  resources :examinations

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :birthday, 
                  :email, 
                  :fathers_name, 
                  :federal_id, 
                  :first_name, 
                  :last_name, 
                  :mothers_name, 
                  :phone1, 
                  :phone2, 
                  :regional_id, 
                  :social_security, 
                  :addresses_attributes
  has_many :addresses
  has_many :events
  has_many :examinations
  #has_many :answers, through: :examinations
  accepts_nested_attributes_for :addresses, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :first_name, :last_name, :mothers_name
  validates_length_of :first_name, :within => 3..30, :allow_blank => true
  validates_numericality_of :federal_id, :allow_blank => true
  validates_uniqueness_of :federal_id, :allow_blank => true  
  def to_label 
    if I18n.locale.to_s == "pt-BR"    
      "#{self.first_name} #{self.last_name} | #{self.mothers_name}"
    else
      "#{self.last_name} , #{self.first_name} | #{self.mothers_name}"
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
      format.pdf {rghost_render :pdf, :report => 'people', :filename => "people022009.pdf"}
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
      format.pdf {rghost_render :pdf, :report => 'people', :filename => "people022009.pdf"}
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
      format.js
    end
  end
  def print
    @people = Person.find :all
    rghost_render :pdf, :report => {:action => 'people', :filename => 'people.pdf'}
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_address_fields.html.erb
<div class="input-group">
  <%= f.input :street, :required => true %>
  <%= f.input :number %>
  <%= f.input :complement%>
  <%= f.association :city, :required => true %>
  <div class="form-actions">
    <%= link_to_remove_association "remove address", f, :class => "btn btn-danger" %>
  </div>  
</div>


app/views/people/_form.html.erb
<%- model_class = Person -%>
<%- model_child = Address -%>
<%= simple_form_for(@person, :html => {:class => 'form-horizontal'}) do |f| %>
  <fieldset>
  	<legend><%= "#{ @person.to_label } " unless @person.to_label.nil?  %>
  	  <h1><p class="text-center"><%=t '.title', :default => model_class.model_name.human.titleize %></p> </h1> 
  	</legend>
	<div class="input-group">
      <%= f.input :first_name, :required => true %>
      <%= f.input :last_name, :required => true %>
      <%= f.input :federal_id %>
      <%= f.input :regional_id %>
      <%= f.input :social_security %>
      <%= f.input :mothers_name, :required => true %>
      <%= f.input :fathers_name %>
      <%= f.input :birthday, as: :date_picker %>
      <%= f.input :phone1 %>
      <%= f.input :phone2 %>
      <%= f.input :email %>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading"><%= model_child.model_name.human.titleize %> </div> 
    <div class="panel-body">
  	  <%= link_to_add_association 'addr address', f, :addresses, :class => "btn btn-default" %>
  	  <%= f.simple_fields_for :addresses do |addr| %>
  	    <%= render "address_fields", :f => addr %>
  	  <% end %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-success" %>
    <%= link_to t('cancel'), :class => 'btn btn-success'%>
  </div>
<% end %>
<br/>

app/views/people/destroy.js.erb
$('tr.<%= @person.id %>').remove();

app/views/people/edit.html.erb
<%= render 'form' %>

<%= link_to t('Show'), @person, :class => "btn btn-primary" %>
<%= link_to t('Back'), root_path, :class => "btn btn-inverse" %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Federal</th>
    <th>Regional</th>
    <th>Social security</th>
    <th>Mothers name</th>
    <th>Fathers name</th>
    <th>Birthday</th>
    <th>Phone1</th>
    <th>Phone2</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.first_name %></td>
    <td><%= person.last_name %></td>
    <td><%= person.federal_id %></td>
    <td><%= person.regional_id %></td>
    <td><%= person.social_security %></td>
    <td><%= person.mothers_name %></td>
    <td><%= person.fathers_name %></td>
    <td><%= l person.birthday, format: :default %></td>
    <td><%= person.phone1 %></td>
    <td><%= person.phone2 %></td>
    <td><%= person.email %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @person.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @person.last_name %>
</p>

<p>
  <b>Federal:</b>
  <%= @person.federal_id %>
</p>

<p>
  <b>Regional:</b>
  <%= @person.regional_id %>
</p>

<p>
  <b>Social security:</b>
  <%= @person.social_security %>
</p>

<p>
  <b>Mothers name:</b>
  <%= @person.mothers_name %>
</p>

<p>
  <b>Fathers name:</b>
  <%= @person.fathers_name %>
</p>

<p>
  <b>Birthday:</b>
  <%= @person.birthday %>
</p>

<p>
  <b>Phone1:</b>
  <%= @person.phone1 %>
</p>

<p>
  <b>Phone2:</b>
  <%= @person.phone2 %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>