config/routes.rb
SurveySupport::Application.routes.draw do
  authenticated :user do
    get "home/index", as: "home"
    root :to => 'home#index'
  end
  get "welcome/index", as: "welcome"
  root :to => 'welcome#index'
  
  devise_for :users  
  
  resources :events
  
  resources :people do
    resources :addresses
  end
  resources :surveys
  resources :cities
  resources :states
  resources :studies do
    member do
      get 'examinations'
    end
  end
  resources :examinations

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :city
  belongs_to :person
  attr_accessible :complement, :number, :postal_code, :street, :person_id
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :examination
  belongs_to :question
  attr_accessible :set, :question_id, :examination_id
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  attr_accessible :description, :inactivated_at, :state_id, :activated
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |city|
        csv << city.attributes.values_at(*column_names)
      end
    end
  end
  def to_label    
    "#{self.description} | #{self.state.abbreviated}"
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :person
  attr_accessible :description, :end_time, :inactivated_at, :start_time, :person_id, :activated, :to_label
  #before_filter :set_activated
  def to_label
    "#{self.description} | #{self.person.to_label}"
  end
end

app/models/examination.rb
class Examination < ActiveRecord::Base
  belongs_to :person
  belongs_to :survey
  has_many :answers
  attr_accessible :reference_date, :answers_attributes, :person_id, :survey_id
  accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :birthday, 
                  :email, 
                  :fathers_name, 
                  :federal_id, 
                  :first_name, 
                  :last_name, 
                  :mothers_name, 
                  :phone1, 
                  :phone2, 
                  :regional_id, 
                  :social_security, 
                  :addresses_attributes
  has_many :addresses
  has_many :events
  has_many :examinations
  #has_many :answers, through: :examinations
  accepts_nested_attributes_for :addresses, :reject_if => :all_blank, :allow_destroy => true
  validates_presence_of :first_name, :last_name, :mothers_name
  validates_length_of :first_name, :within => 3..30, :allow_blank => true
  validates_numericality_of :federal_id, :allow_blank => true
  validates_uniqueness_of :federal_id, :allow_blank => true  
  def to_label 
    if I18n.locale.to_s == "pt-BR"    
      "#{self.first_name} #{self.last_name} | #{self.mothers_name}"
    else
      "#{self.last_name} , #{self.first_name} | #{self.mothers_name}"
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers  
  attr_accessible :activated, :description_question, :mandatory, :type_field, :survey_id, :answers_attributes
  def to_label
    "#{self.description_question}"
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  #include Mongoid::Document
  
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :abbreviated, :description, :inactivated_at, :activated
  attr_accessor :activated
  def to_label    
    "#{self.description}"
  end  
  def activated?
    unless self.inactivated_at = nil then
      self.inactivated_at > Time.current
    else
      true
    end
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :activated, :description, :questions_attributes
  has_many :questions
  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true
  def to_label
    "#{self.description}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable
  validates_uniqueness_of :email, :case_sensitive => false
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :role_ids, :as => :admin
  # attr_accessible :title, :body
  def to_label    
    "#{self.email}"
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  def index
    @surveys = Survey.find(:all, :conditions => {:activated => true})

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @survey = Survey.find(params[:id])
    
  end
  def edit
    @survey = Survey.find(params[:id])
  end
  def examinations
    @survey = Survey.find(params[:id])
    @examination = Examination.new
    @examination.survey_id = @survey.id
    @survey.questions.each do |q|
      @examination.answers.build(question_id: q.id)
                   
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @examination }
    end    
  end
  # GET /people/new
  # GET /people/new.json
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/studies/examinations.html.erb
<%- model_class = Examination -%>
<%= simple_form_for(@examination, :html => {:class => "form form-horizontal"}) do |f| %>
  <fieldset>
  	<legend><%= "#{ @examination.survey.description } " unless @examination.survey.description.nil?  %>
  	  <h1><p class="text-center"><%=t '.title', :default => model_class.model_name.human.titleize %></p> </h1> 
  	</legend>
  	<div class="input-group">
      <%= f.association :survey, :disabled => true %>
      <%= f.input :reference_date, as: :date_picker%>
      <%= f.association :person %>
    </div>
  </fieldset>
  <div class="panel panel-default">
    <div class="panel panel-body">
      <%= f.simple_fields_for :answers  do |a| %>
        <%= a.association :question, :disabled => true %>
        <%= a.input :set, as: :text, :input_html => {:cols => 50, :rows => 3}%>
      <% end %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-success" %>
    <%= link_to t('cancel'), root_path, :class => 'btn btn-inverse'%>
  </div>
<% end %>

app/views/studies/index.html.erb
<h1>Listing surveys</h1>

<table>
  <tr>
  	<th>id</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= link_to survey.id, survey_path(survey) %></td>
    <td><%= survey.description %></td>
    <td><%= link_to 'Set', examinations_study_path(survey) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_survey_path %>

app/views/studies/new.html.erb
<% @surveys.each do |s| %>
  <p> <%= s.description %> </p>
<% end %>
<%= link_to "add", :action => :research, :controller => :studies %>

app/views/studies/show.html.erb
<%= simple_form_for(@research) do |f| %>
  <div class="form-inputs">
  	<%= f.association :person %>
  	<div class="questions">
  	<%= f.simple_fields_for :answers do |q| %>
  	  <%= q. %>
  	  <%= q.input :set %>
  	  <% end %>
  	</div> 
  </div>
  <%= f.button :submit %>
<% end %>