config/routes.rb
SurveySupport::Application.routes.draw do
  authenticated :user do
    get "home/index", as: "home"
    root :to => 'home#index'
  end
  get "welcome/index", as: "welcome"
  root :to => 'welcome#index'
  
  devise_for :users  
  
  resources :events
  
  resources :people do
    resources :addresses
  end
  resources :surveys
  resources :cities
  resources :states
  resources :studies do
    member do
      get 'examinations'
    end
  end
  resources :examinations

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :activated, :description, :questions_attributes
  has_many :questions
  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true
  def to_label
    "#{self.description}"
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
  def answers
    @people = Person.all
    @questions = @survey.questions
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= simple_form_for(@survey, :html => {:class => 'form form-horizontal'}) do |f| %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :activated %>
  </div>
  <div id="questions">
  	<%= link_to_add_association 'add questions', f, :questions, :class => "btn btn-default" %>
 	<%= f.simple_fields_for :questions do |q| %>
  	  <%= render "question_fields", :f => q %>
  	<% end %>  	  	
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/surveys/_question_fields.html.erb
<div class="nested-fields">
  <%= f.input :description_question %> 
  <%= f.input :mandatory %>
  <%= f.input :activated%>
  <div class="form-actions">
    <%= link_to_remove_association "remove question", f, :class => "btn btn-danger" %>
  </div>  
</div>

app/views/surveys/answers.html.erb
<%= form_for(@survey) do |f| %>
  <% @people.each do |participant| %>
  <h3><%= participant.last_name %></h3>
  <table>
    <thead>
      <tr>
        <td>Questions</td>
        <td>Answer</td>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
      <tr>
        <td><%= question.description_question %></td>
        <td>
        <%= f.fields_for :questions, question do |q| %>
          <%= q.fields_for :answers, question.answers.find_or_initialize_by(participant: participant) do |a| %>
            <%= a.text_area :content %>
            <%= a.hidden_field :person_id, participant.id %>
          <% end %>
        <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Activated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.description %></td>
    <td><%= survey.activated %></td>
    <td><%= link_to 'Show', survey %></td>
    <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
    <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @survey.description %>
</p>

<p>
  <b>Activated:</b>
  <%= @survey.activated %>
</p>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>