config/routes.rb
SurveySupport::Application.routes.draw do
  authenticated :user do
    get "home/index", as: "home"
    root :to => 'home#index'
  end
  get "welcome/index", as: "welcome"
  root :to => 'welcome#index'
  
  devise_for :users  
  
  resources :events
  
  resources :people do
    resources :addresses
  end
  resources :surveys
  resources :cities
  resources :states
  resources :studies do
    member do
      get 'examinations'
    end
  end
  resources :examinations

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  attr_accessible :description, :inactivated_at, :state_id, :activated
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |city|
        csv << city.attributes.values_at(*column_names)
      end
    end
  end
  def to_label    
    "#{self.description} | #{self.state.abbreviated}"
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.order(:id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
      format.csv { send_data @cities.to_csv}
      format.xls # {send_data @cities.to_csv(col_sep: "\t")}
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%- model_class = City -%>
<%= simple_form_for(@city, :html => {:class => 'form form-horizontal'}) do |f| %>
  <fieldset>
  	<legend><%= "#{ @city.description } " unless @city.description.nil?  %>
  	  <h1><p class="text-center"><%=t '.title', :default => model_class.model_name.human.titleize %></p> </h1> 
  	</legend>
	<div class="input-group">
      <%= f.input :description, :required => true %>
      <%= f.association :state %>        
    </div>
  </fieldset>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-success' %>
    <%= link_to t(".cancel"), root_path, :class => "btn btn-inverse" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<%= render 'form' %>
<div class="form-actions">
  <%= link_to t('show'), @city, :class => "btn btn-primary" %> 
  <%= link_to t('Back'), cities_path, :class => 'btn btn-inverse' %>
</div>

app/views/cities/index.html.erb
<%- model_class = City -%>
<div class='page-header'>
  <h1><p class="text-center"><%=t '.title', :default => model_class.model_name.human.pluralize %></p> </h1>  
</div>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:state_id) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @cities.each do |city| %>  
    <tr>
      <td><%= link_to city.id, city_path(city) %></td>
      <td><%= city.description %></td>
      <td><%= city.state.to_label %></td>
      <td><%= link_to('<i class="icon-eye-open"/>'.html_safe, city, :title => t('show') + "#{ }" + "#{ city.description }")  %></td>
      <td><%= link_to('<i class="icon-edit"/>'.html_safe, edit_city_path(city), :title => t('edit') + "#{ city.description }") %></td>
      <td><%= link_to('<i class="icon-remove"/>'.html_safe, city, :method => :delete, :confirm => t('confirmation') + "#{ city.description }", :title => "Delete #{ city.description }") %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<div class="form-actions">
  <%= link_to t('new'), new_city_path, :class => "btn btn-primary" %>
  <%= link_to t('back'), root_path, :class => "btn btn-inverse"%>
  <%= link_to "CSV", cities_path(format: "csv")%>
  <%= link_to "Excel", cities_path(format: "xls")%>
</div>

app/views/cities/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">State</Data></Cell>
      </Row>
    <% @cities.each do |city| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= city.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= city.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= city.state.to_label %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/cities/new.html.erb
<%= render 'form' %>
<div class="form-actions">
  <%= link_to t('back'), cities_path, :class => "btn btn-inverse" %>
</div>

app/views/cities/show.html.erb
<%- model_class = City -%>
<div class='page-header'>
  <h1><p class="text-center"><%=t '.title', :default => model_class.model_name.human.titleize %></p> </h1>  
</div>
  <fieldset>
    <legend> <%= @city.description%> </legend>
    <dl class="dl-horizontal">
      <dt>
        <span class="label label-info">
      	  <%= model_class.human_attribute_name(:id) %>:
      	</span>
      </dt>
      <dd>
      	<%= @city.id %>
      </dd>
      <dt>
      	<span class="label label-info">
      	  <%= model_class.human_attribute_name(:description) %>:
      	</span>
      </dt>
      <dd>
      	<%= @city.description %>
      </dd>
      <dt>
      	<span class="label label-info">
      	  <%= model_class.human_attribute_name(:state_id) %>:
        </span>
      </dt>
      <dd>
      	<%= @city.state_id %> - <%= @city.state.description %>
      </dd>
    </dl>	
  </fieldset>
<div class="form-actions">
  <%= link_to t('edit'), edit_city_path(@city), :class => "btn btn-primary" %>
  <%= link_to t('back'), cities_path, :class => "btn btn-inverse" %>
</div>